config/routes.rb
SmokenRecipes::Application.routes.draw do
  
  get "sessions/new"

  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  resources :recipes,  :only => [:create, :destroy]

  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'

  
  root :to => 'pages#home'

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  attr_accessible :cooking_time, :description, :directions, :ingredients, :prep_time, :recipe_name

  belongs_to :user

  validates :cooking_time, :presence => true, :length => { :maximum => 20 }
  validates :description,  :presence => true, :length => { :maximum => 140 }
  validates :directions,   :presence => true
  validates :ingredients,  :presence => true
  validates :prep_time,    :presence => true, :length => { :maximum => 20 }
  validates :recipe_name,  :presence => true, :length => { :maximum => 40}
  validates :user_id,      :presence => true 

  default_scope :order => 'recipes.created_at DESC'
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :password
  attr_accessible :email, :name, :password, :password_confirmation

  has_many :recipes, :dependent => :destroy

  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :name,  :presence    => true,
  					:length      => { :maximum => 50 }
  validates :email, :presence    => true,
  					:format      => { :with => email_regex },
  					:uniqueness  => { :case_sensitive => false }
  validates :password, :presence     => true,
  					   :confirmation => true,
  					   :length       => { :within => 6..40 }
  before_save :encrypt_password

  def has_password?(submitted_password)
    encrypted_password = encrypt(submitted_password)
  end

  def self.authenticate(email, submitted_password)
    user = find_by_email(email)
    return nil if user.nil?
    return user if user.has_password?(submitted_password)
  end

  def self.authenticate_with_salt(id, cookie_salt)
    user = find_by_id(id)
    (user && user.salt == cookie_salt) ? user : nil
  end

  def feed
    Recipe.where("user_id = ?", id)
  end

  private

  def encrypt_password
    self.salt = make_salt unless has_password?(password)
  	self.encrypted_password = encrypt(password)
  end

  def encrypt(string)
  	secure_hash("#{salt}--#{string}")
  end

  def make_salt
    secure_hash("#{Time.now.utc}--#{password}")
  end

  def secure_hash(string)
    Digest::SHA2.hexdigest(string)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  	@title = "Home"
    if signed_in?
      @recipe = Recipe.new
      @feed_items = current_user.feed.paginate(:page => params[:page])
    end
  end

  def contact
  	@title = "Contact"
  end

  def about
  	@title = "About"
  end

  def help
  	@title = "Help"
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
	before_filter :authenticate, :only => [:create, :destroy]
	before_filter :authorized_user, :only => :destroy

	def index
	end

	def create
		@recipe = current_user.recipes.build(params[:recipe])
		if @recipe.save
			flash[:success] = "Recipe created!"
			redirect_to root_path
		else
			@feed_items = []
			render 'pages/home'
		end
	end

	def destroy
		@recipe.destroy
		redirect_back_or root_path
	end

	private

	  def authorized_user
	  	@recipe = current_user.recipes.find_by_id(params[:id])
	  	redirect_to root_path if @recipe.nil?
	  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	protect_from_forgery
	include SessionsHelper
  def new
  	@title = "Sign in"
  end

  def create
  	user = User.authenticate(params[:session][:email],
  							 params[:session][:password])
  	if user.nil?
  		flash.now[:error] = "Invalid email/password combination."
  		@title = "Sign in"
  		render 'new'
  	else
  		sign_in user
  		redirect_to user
  	end
  end

  def destroy
  	sign_out
  	redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_filter :authenticate, :only => [:index, :edit, :update]
  before_filter :correct_user, :only => [:edit, :update]
  before_filter :admin_user,   :only => :destroy
  
  def index
  	@title = "All users"
    @users = User.paginate(page: params[:page])
  end

  def show
  	@user = User.find(params[:id])
  	@title = @user.name
    @recipes = @user.recipes.paginate(:page => params[:page])
  end

  def new
  	@user = User.new
  	@title = "Sign up"
  end

  def create 
  	@user = User.new(params[:user])
  	if @user.save
  		sign_in @user
  		flash[:success] = "Welcome to the Smoken Recipes!"
  		redirect_to @user
  	else
  		@title = "Sign up"
  		render 'new'
  	end
  end

  def edit
  	@user = User.find(params[:id])
  	@title = "Edit user"
  end

  def update 
  	@user = User.find(params[:id])
  	if @user.update_attributes(params[:user])
  		flash[:success] = "Profile updated."
  		redirect_to @user
  	else
  		@title = "Edit user"
  		render 'edit'
  	end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User destroyed."
    redirect_to users_path
  end

  private

    def authenticate
      deny_access unless signed_in?
    end

    def correct_user
    	@user = User.find(params[:id])
    	redirect_to(root_path) unless current_user?(@user)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
	def title
		base_title = "Smoken Recipes"
		if @title.nil?
			base_title
		else
			"#{base_title} | #{@title}"
		end
	end

	def logo
	  image_tag("logo.png", :alt => "Smoken Recipes", :class => "round")
	end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  def sign_in(user)
  	cookies.permanent.signed[:remember_token] = [user.id, user.salt]
  	self.current_user = user
  end
  
  def current_user=(user)
  	@current_user = user
  end

  def current_user
  	@current_user ||= user_from_remember_token
  end

  def signed_in?
  	!current_user.nil?
  end

  def sign_out
  	cookies.delete(:remember_token)
  	self.current_user = nil
  end

  def current_user?(user)
    user == current_user
  end

  def deny_access
    store_location
    redirect_to signin_path, :notice => "Please sign in to access this page."
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    clear_return_to
  end

  def authenticate
    deny_access unless signed_in?
  end
      
  def deny_access
    store_location
    redirect_to signin_path, :notice => "Please sign in to access this page"
  end

  private

    def user_from_remember_token
    	User.authenticate_with_salt(*remember_token)
    end

    def remember_token
    	cookies.signed[:remember_token] || [nil, nil]
    end

    def store_location
      session[:return_to] = request.fullpath
    end

    def clear_return_to
      sesson[:return_to] = nil
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer>
	<nav class="round">
		<ul>
		  <li><%= link_to "About", about_path %></li>
		  <li><%= link_to "Contact", contact_path %></li>
		  <li><%= link_to "News", '#' %></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
  	  <header>
  	  	<%= link_to logo, root_path %>
  	  	<nav class="round">
  	  	  <ul class="menu" id="menu">
 			<li><%= link_to "Home", root_path %></li>
 			<li><%= link_to "Help", help_path %></li>
 			<% if signed_in? %>
 			<li><%= link_to "Users", users_path %></li>

 		    	<li><a href="#" class="menulink">User Tools</a>
 		    		<ul>
 			          <li><%= link_to "Profile", current_user %></li>
 			          <li><%= link_to "settings", edit_user_path(current_user) %></li>
 			          <li><%= link_to "Sign out", signout_path, :method => :delete %></li>
 			        </ul>
 			    </li>
 			<% else %>
 			<li><%= link_to "Sign in", signin_path %></li>
 			<% end %>
  	  	  </ul>
  	  	</nav>
  	  </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  	<title><%= @title %></title>
    <%= csrf_meta_tag %>
    <!--[if lt IE 9]>
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->    
    <%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
    <%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
    <!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
    <%= stylesheet_link_tag 'application', :media => 'screen' %>
    <%= javascript_include_tag "application" %>
    <%= javascript_include_tag "dropdown" %>
  </head>
  <body>
  	<div class="container">
  	  <%= render 'layouts/header' %>
  	  <section class="round">
        <% flash.each do |key, value| %>
          <div class="flash <%= key %>"><%= value %></div>
          <% end %> 
        <%= yield %>
      </section>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
    <script type="text/javascript">
  var menu=new menu.dd("menu");
  menu.init("menu","menuhover");
</script>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About Us</h1>
  <p>
    My name is Tyler Stuart. Two of my favorite things are programming and cooking anything outdoors. 
    This Site is was created to help me become better at programming and to help others improve there 
    outdoor cooking skills. 
  </p>

app/views/pages/contact.html.erb
<h1>Contact</h1>
  <p>
    Form for contact soon to come.
  </p>

app/views/pages/help.html.erb
<h1>Help</h1>
  <p>
    get help on this page.
  </p>

app/views/pages/home.html.erb
<% if signed_in? %>
  <table class="front" summary="For signed-in users">
    <tr>
      <td class="main">
        <h1 class="recipe">New Recipe!</h1>
        <%= render 'shared/recipe_form' %>
        <%= render 'shared/feed' %>
      </td>
      <td class="sidebar round">
        <%= render 'shared/user_info' %>
      </td>
    </tr>
  </table>
<% else %>
  <h1>Sample App</h1>

  <p>
    This is the home page for the
    <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
    sample application.
  </p>

  <%= link_to "Sign up now!", signup_path, :class => "signup_button round" %>
<% end %>

app/views/recipes/_recipe.html.erb
<tr>
  <td class="recipe">
  	<span class="recipe_name"><%= recipe.recipe_name %></span>
    <span class="timestamp">
      Posted <%= time_ago_in_words(recipe.created_at) %> ago.
    </span>
  </td>
  <% if current_user?(recipe.user) %>
    <td>
      <%= link_to "delete", recipe, :method => :delete,
      								:confirm => "You sure?",
      								:title => recipe.recipe_name %>
    </td>
  <% end %>
</tr>

app/views/shared/_error_message.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %> 
        prohibited this <%= object.class.to_s.underscore.humanize.downcase %> 
        from being saved:</h2>
    <p>There were problems with the following fields:</p>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% unless @feed_items.empty? %>
  <table class="recipes" summary="User recipes">
  	<%= render :partial => 'shared/feed_item', :collection => @feed_items %>
  </table>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<tr>
  <td class="recipe">
    <span class="user">
      <%= link_to feed_item.user.name, feed_item.user %>
    </span>
    <span class="recipe"><%= feed_item.recipe_name %></span>
    <span class="timestamp">
      Posted <%= time_ago_in_words(feed_item.created_at) %> ago.
    </span>
  </td>
  <% if current_user?(feed_item.user) %>
    <td>
      <%= link_to "delete", feed_item, :method => :delete,
                      :confirm => "You sure?",
                      :title => feed_item.recipe_name %>
    </td>
  <% end %>
</tr>

app/views/shared/_recipe_form.html.erb
<%= form_for @recipe do |f| %>
<%= render 'shared/error_message', :object => f.object %>
  <div class="field">
    <%= f.label :recipe_name %><br />
    <%= f.text_field :recipe_name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :ingredients %><br />
    <%= f.text_area :ingredients %>
  </div>
  <div class="field">
    <%= f.label :directions %><br />
    <%= f.text_area :directions %>
  </div>
  <div class="field">
    <%= f.label :prep_time %><br />
    <%= f.text_field :prep_time %>
  </div>
  <div class="field">
    <%= f.label :cooking_time %><br />
    <%= f.text_field :cooking_time %>
  </div>
  <div class="actions">
    <%= f.submit "Submit" %>
  </div>
<% end %>

app/views/shared/_user_info.html.erb
<div class="user_info">
  <a href="<%= user_path(current_user) %>">
    <span class="user_name">
      <%= current_user.name %>
    </span>
    <span class="recipes">
      <%= pluralize(current_user.recipes.count, "recipe") %>
    </span>
  </a>
</div>

app/views/users/edit.html.erb
<h1>Edit user</h1>

<%= form_for(@user) do |f| %>
  <%= render 'shared/error_message', :object => f.object %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Confirmation" %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit "Update" %>
  </div>
<% end %>

app/views/users/index.html.erb
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= link_to user.name, user %>
      <% if current_user.admin? %>
      | <%= link_to "delete", user, :method => :delete, :confirm => "You sure?",
      								:title => "Delete #{user.name}" %>
      <% end %>
    </li>
  <% end %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= form_for(@user) do |f| %>
  <%= render 'shared/error_message', :object => f.object %>
  <div class="field">
  	<%= f.label :name %><br />
  	<%= f.text_field :name %>
  </div>
  <div class="field">
  	<%= f.label :email %><br />
  	<%= f.text_field :email %>
  </div>
  <div class="field">
  	<%= f.label :password %><br />
  	<%= f.password_field :password %>
  </div>
  <div class="field">
  	<%= f.label :password_confirmation, "Confirmation" %><br />
  	<%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
  	<%= f.submit "Sign up" %>
  </div>
<% end %>

app/views/users/show.html.erb
<table class="profile" summary="profile information" >
  <tr>
  	<td class="main">
      <h1>
        <%= @user.name %>
      </h1>
      <% unless @user.recipes.empty? %>
        <table class="recipes" summary="User recipes">
          <%= render @recipes %>
        </table>
        <%= will_paginate @recipes %>
      <% end %>
    </td>
    <td class="sidebar round">
    	<strong>Name</strong> <%= @user.name %><br />
    	<strong>URL</strong> <%= link_to user_path(@user), @user %><br />
      <strong>Recipes</strong> <%= @user.recipes.count %>
    </td>
  </tr>
</table>